batch_size: 32
dataset: imagenet
num_workers: 8
results_dir: results/robustness/features/giant-reg-rob
seed: 0
surrogate:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitg14_reg
surrogate_state_dict: results/dinov2_vitg14_reg/last.ckpt
victim:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitg14_reg
victim_state_dict: results/dinov2_vitg14_reg/last.ckpt
