batch_size: 32
dataset: imagenet
num_workers: 8
results_dir: results/robustness/features/large-reg-rob
seed: 0
surrogate:
  enbable_robust: false
  n_rtokens: 0
  name: dinov2_vitl14_reg
surrogate_state_dict: results/dinov2_vitl14_reg/last.ckpt
victim:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitl14_reg
victim_state_dict: results/dinov2_vitl14_reg/last.ckpt
