batch_size: 32
dataset: imagenet
num_workers: 8
results_dir: results/robustness/features/large-reg
seed: 0
surrogate:
  enbable_robust: false
  n_rtokens: 0
  name: dinov2_vitl14_reg
victim:
  enbable_robust: false
  n_rtokens: 0
  name: dinov2_vitl14_reg
