batch_size: 32
dataset: imagenet
num_workers: 8
results_dir: results/robustness/features/small-rob
seed: 0
surrogate:
  enbable_robust: false
  n_rtokens: 0
  name: dinov2_vits14
surrogate_state_dict: results/dinov2_vits14/last.ckpt
victim:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vits14
victim_state_dict: results/dinov2_vits14/last.ckpt
