dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 50
  name: dinov2_vitb14
results_dir: results/token_ablation/base_50
run_name: token_ablation - base - 50
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 200
  mode: max
  num_workers: 16
  optimizer: Adam
