image: continuumio/miniconda3:latest

stages:
  - conda
  - test
  - lint

conda:
  stage: conda
  script:
    - conda create --name rtokens --file requirements.txt
    - conda activate rtokens

test:
  stage: test
  script:
    - pytest tests/
    - echo "Tests completed"

lint:
  stage: lint
  script:
    - pre-commit install
    - pre-commit run --all-files
