model:
  n_rtokens: 10
  name: dinov2_vitb14
  return_cls: false
  checkpoint_path: results/default/last.ckpt
results_dir: results/default/segmentation
run_name: default - segmentation
seed: 0
train:
  batch_size: 2 # At most (2**31 - 1) // (image_size ** 2 * 3688)
  checkpoint_freq: 5000
  image_size: 448
  lr: 0.00005
  max_steps: 50000
  num_workers: 16
  optimizer: Adam
