batch_size: 32
dataset: imagenet
num_workers: 8
results_dir: results/robustness/class/large-rob
seed: 0
surrogate:
  backbone_kwargs:
    enbable_robust: false
    n_rtokens: 0
    name: dinov2_vitl14
  backbone_path: NOPATH
  head_path: results/dinov2_vitl14/linear/model_final.pth
  head_classifier_name: classifier_1_blocks_avgpool_True_lr_0_01000
victim:
  backbone_kwargs:
    enbable_robust: true
    n_rtokens: 10
    name: dinov2_vitl14
  backbone_path: results/dinov2_vitl14/last.ckpt
  head_path: results/dinov2_vitl14/linear/model_final.pth
  head_classifier_name: classifier_1_blocks_avgpool_True_lr_0_01000
