attack:
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
  name: pgd
  steps: 30
batch_size: 8
dataset: imagenet
num_workers: 16
model:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitb14_reg
results_dir: results/default
seed: 0
state_dict: results/default/last.ckpt
