surrogate:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitb14_reg_ade20k_linear_config_without_rtokens.py"
  ckpt_path: "results/dinov2_vitb14_reg/segmentation/without_rtokens/latest.pth"
victim:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitb14_reg_ade20k_linear_config_without_rtokens.py"
  ckpt_path: "results/dinov2_vitb14_reg/segmentation/without_rtokens/latest.pth"
samples_per_gpu: 2
results_dir: "results/robustness/segmentation/base-reg"
