surrogate:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitg14_reg_ade20k_linear_config_without_rtokens.py"
  ckpt_path: "results/dinov2_vitg14_reg/segmentation/without_rtokens/latest.pth"
victim:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitg14_reg_ade20k_linear_config_without_rtokens.py"
  ckpt_path: "results/dinov2_vitg14_reg/segmentation/without_rtokens/latest.pth"
samples_per_gpu: 2
result_dir: "results/robustness/segmentation/giant-reg"
