surrogate:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitl14_ade20k_linear_config.py"
  ckpt_path: "results/dinov2_vitl14/segmentation/latest.pth"
victim:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitl14_ade20k_linear_config.py"
  ckpt_path: "results/dinov2_vitl14/segmentation/latest.pth"
samples_per_gpu: 128
result_dir: "results/robustness/segmentation/large-rob"
