surrogate:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitl14_reg_ade20k_linear_config_without_rtokens.py"
  ckpt_path: "results/dinov2_vitl14_reg/segmentation/without_rtokens/latest.pth"
victim:
  cfg_path: "configs/robustness/segmentation/cfgs/dinov2_vitl14_reg_ade20k_linear_config.py"
  ckpt_path: "results/dinov2_vitl14_reg/segmentation/latest.pth"
samples_per_gpu: 2
result_dir: "results/robustness/segmentation/large-reg-rob"
