dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 10
  name: openclip_vith14
results_dir: results/openclip_vith14
run_name: openclip_vith14 - train robustness
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 300
  mode: max
  num_workers: 16
  optimizer: Adam
