model:
  n_rtokens: 10
  name: dinov2_vitb14
  return_cls: false
  checkpoint_path: results/default/last.ckpt
results_dir: results/default/classification
run_name: default - classification
seed: 0
train:
  batch_size: 128
  checkpoint_freq: 1250
  lr: 0.0001
  max_steps: 12500
  num_workers: 16
  optimizer: Adam
