model:
  n_rtokens: 10
  name: dinov2_vitb14
  return_cls: false
  checkpoint_path: /srv/beegfs/scratch/users/p/pulfer/robustness_tokens/results/dinov2_vitb14_10tokens/last.ckpt
results_dir: /srv/beegfs/scratch/users/p/pulfer/robustness_tokens/results/dinov2_vitb14_10tokens/depth
run_name: dinov2_vitb14_10tokens - depth
seed: 0
train:
  batch_size: 32
  checkpoint_freq: 1000
  image_width: 616
  image_height: 462
  lr: 0.0001
  max_steps: 10000
  num_workers: 8
  optimizer: AdamW
