dataset: imagenet
attack:
  steps: 30
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
model:
  name: dinov2_vitb14
  return_cls: False
  n_rtokens: 10
train:
  optimizer: Adam
  lr: 0.001
  batch_size: 128
  num_workers: 16
  criterion: CosineSimilarity
  mode: max
  max_steps: 300
  steps_per_batch: 1
  val_every_n_steps: 30
  grad_log_freq: 30
results_dir: results/default
run_name: default
seed: 0
