data:
  dataset: imagenet
  split: train
  data_dir: /data/imagenet
attack:
  steps: 30
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
model:
  name: dinov2_vitb14
  return_cls: False
  n_rtokens: 1
train:
  optimizer: Adam
  lr: 0.001
  batch_size: 64
  num_workers: 16
  criterion: CosineSimilarity
  mode: max
  max_steps: 1000
  val_every_n_steps: 100
  steps_per_batch: 1
results_dir: results/default
run_name: default
seed: 0
