data:
  dataset: imagenet
  split: train
  data_dir: /data/imagenet
attack:
  steps: 350
  eps: 0.031
  lr: 0.0004
  max_mse: 0.0001
model:
  name: dinov2_vits14
  return_cls: False
  n_rtokens: 1
train:
  optimizer: Adam
  lr: 0.001
  batch_size: 32  # 0 -> finds the largest possible batch size
  num_workers: 16  # 0 -> uses cpu count
  criterion: CosineSimilarity
  mode: max
  max_steps: 1_000
  val_every_n_steps: 100
  steps_per_batch: 1
results_dir: results/default
run_name: default
seed: 0
