attack:
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
  name: pgd
  steps: 30
dataset: imagenet
model:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitb14_reg
results_dir: results/default
run_name: main - train robustness
seed: 0
train:
  batch_size: 8
  checkpoint_freq: 50
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 50
  mode: max
  num_workers: 16
  optimizer: Adam
