attack:
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
  name: pgd
  steps: 30
batch_size: 32
dataset: imagenet
num_workers: 8
results_dir: results/dinov2_vitb14_reg/robustness
seed: 0
surrogate:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitb14_reg
surrogate_state_dict: results/dinov2_vitb14_reg/last.ckpt
victim:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitb14_reg
victim_state_dict: results/dinov2_vitb14_reg/last.ckpt
