#!/bin/bash

##### WITH RTOKENS #####
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vits14_reg.yaml --pretrained-weights results/dinov2_vits14_reg/last.pth --output-dir results/dinov2_vits14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vits14.yaml --pretrained-weights results/dinov2_vits14/last.pth --output-dir results/dinov2_vits14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitb14_reg.yaml --pretrained-weights results/dinov2_vitb14_reg/last.pth --output-dir results/dinov2_vitb14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitb14.yaml --pretrained-weights results/dinov2_vitb14/last.pth --output-dir results/dinov2_vitb14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitl14_reg.yaml --pretrained-weights results/dinov2_vitl14_reg/last.pth --output-dir results/dinov2_vitl14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitl14.yaml --pretrained-weights results/dinov2_vitl14/last.pth --output-dir results/dinov2_vitl14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitg14_reg.yaml --pretrained-weights results/dinov2_vitg14_reg/last.pth --output-dir results/dinov2_vitg14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-sip-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitg14.yaml --pretrained-weights results/dinov2_vitg14/last.pth --output-dir results/dinov2_vitg14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-sip-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080


##### WITHOUT RTOKENS #####
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vits14_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vits14_pretrain.pth --output-dir results/dinov2_vits14/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vits14_reg4_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vits14_reg4_pretrain.pth --output-dir results/dinov2_vits14_reg/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vitb14_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vitb14_pretrain.pth --output-dir results/dinov2_vitb14/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vitb14_reg4_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vitb14_reg4_pretrain.pth --output-dir results/dinov2_vitb14_reg/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vitl14_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vitl14_pretrain.pth --output-dir results/dinov2_vitl14/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vitl14_reg4_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vitl14_reg4_pretrain.pth --output-dir results/dinov2_vitl14_reg/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vitg14_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vitg14_pretrain.pth --output-dir results/dinov2_vitg14/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-sip-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./src/dinov2/dinov2/configs/eval/vitg14_reg4_pretrain.yaml --pretrained-weights ./src/dinov2/weights/dinov2_vitg14_reg4_pretrain.pth --output-dir results/dinov2_vitg14_reg/without_rtokens/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-sip-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
