#!/bin/bash

#PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vits14_reg.yaml --pretrained-weights results/dinov2_vits14_reg/last.pth --output-dir results/dinov2_vits14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
#PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vits14.yaml --pretrained-weights results/dinov2_vits14/last.pth --output-dir results/dinov2_vits14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

#PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitb14_reg.yaml --pretrained-weights results/dinov2_vitb14_reg/last.pth --output-dir results/dinov2_vitb14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
#PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitb14.yaml --pretrained-weights results/dinov2_vitb14/last.pth --output-dir results/dinov2_vitb14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

#PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitl14_reg.yaml --pretrained-weights results/dinov2_vitl14_reg/last.pth --output-dir results/dinov2_vitl14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
#PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitl14.yaml --pretrained-weights results/dinov2_vitl14/last.pth --output-dir results/dinov2_vitl14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-cui-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080

PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitg14_reg.yaml --pretrained-weights results/dinov2_vitg14_reg/last.pth --output-dir results/dinov2_vitg14_reg/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-sip-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
PYTHONPATH=./src/dinov2 python ./src/dinov2/dinov2/run/eval/linear.py --config-file ./configs/eval/classification/vitg14.yaml --pretrained-weights results/dinov2_vitg14/last.pth --output-dir results/dinov2_vitg14/linear --train-dataset ImageNet:split=TRAIN:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --val-dataset ImageNet:split=VAL:root=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/imagenet:extra=/srv/beegfs/scratch/users/p/pulfer/datasets/IMAGENET/extra --partition private-sip-gpu --nodes 1 --gpus 1 --batch-size 128 --timeout 10080
