attack:
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
  steps: 30
dataset: imagenet
model:
  n_rtokens: 10
  name: dinov2_vitb14
  return_cls: false
results_dir: results/default
run_name: default
seed: 0
train:
  batch_size: 128
  checkpoint_freq: 30
  criterion: CosineSimilarity
  lr: 0.001
  max_steps: 3
  mode: max
  num_workers: 16
  optimizer: Adam
  steps_per_batch: 1
