attack:
  eps: 0.0314
  lr: 0.01
  max_mse: 0.0001
  steps: 30
dataset: imagenet
model:
  n_rtokens: 10
  name: dinov2_vits14
  return_cls: false
results_dir: results/small
run_name: small
seed: 0
train:
  batch_size: 256
  criterion: CosineSimilarity
  grad_log_freq: 30
  lr: 0.001
  max_steps: 300
  max_val_steps: 10
  mode: max
  num_workers: 16
  optimizer: Adam
  steps_per_batch: 1
  val_every_n_steps: 30
