batch_size: 1
dataset: imagenet
layer_idxs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
model:
  enbable_robust: true
  n_rtokens: 10
  name: dinov2_vitl14
num_workers: 8
rtokens: 'results/dinov2_vitl14/rtokens.pt'
savedir: 'results/massive_activations'
seed: 0